/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lights.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Lights(props) {
  const { nodes, materials } = useGLTF("/lights.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-2.636, 3.561, -4.088]}
        rotation={[1.11, -0.044, -3.107]}
        scale={0.092}
      >
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <group
        position={[-1.049, 3.561, -4.088]}
        rotation={[1.11, -0.044, -3.107]}
        scale={0.092}
      >
        <mesh
          geometry={nodes.Cylinder002_1.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cylinder002_2.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <group
        position={[0.913, 3.561, -4.088]}
        rotation={[1.11, -0.044, -3.107]}
        scale={0.092}
      >
        <mesh
          geometry={nodes.Cylinder003_1.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cylinder003_2.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <group
        position={[2.5, 3.561, -4.088]}
        rotation={[1.11, -0.044, -3.107]}
        scale={0.092}
      >
        <mesh
          geometry={nodes.Cylinder004.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cylinder004_1.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.010"]}
        position={[0, 3.917, -4.045]}
        scale={[2.991, 0.039, -0.045]}
      />
    </group>
  );
}

useGLTF.preload("/lights.gltf");
