/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 actTShirtOversized.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ActTShirtOversized(props) {
  const { nodes, materials } = useGLTF("/actTShirtOversized.glb");
  return (
    <group {...props} dispose={null} scale={4} position={[0, -3.8, 0]}>
      <mesh
        geometry={nodes.back_1_Node.geometry}
        material={materials["Cotton Texture"]}
      />
      <mesh
        geometry={nodes["TSHIRTREGULARSSTGM-COL_Node"].geometry}
        material={materials.Collar}
      />
    </group>
  );
}

useGLTF.preload("/actTShirtOversized.glb");
