/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Hoodie({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/hoodie.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.blank_hoodie002.geometry}
        material={materials.body}
        // position={[-0.04, -0.33, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.blank_hoodie001.geometry}
        material={materials.decal}
        // position={[-0.04, -0.33, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/hoodie.gltf");
